=== soroush/libmarl-protocols/docs/mdp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
    <xs:documentation xml:lang="en">
        Markov Decision Process Document Format
    </xs:documentation>
</xs:annotation>

<xs:simpleType name="id_type">
    <xs:restriction base="xs:nonNegativeInteger"/>
</xs:simpleType>

<xs:simpleType name="title_type">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="state_pointer_type">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="probability_type">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="1.0"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="environment">
<xs:complexType>
    <xs:sequence>
        <xs:element name="title" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="states" maxOccurs="1" minOccurs="1">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="state" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="id" type="id_type" use="required"/>
                            <xs:attribute name="title" type="title_type" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="actions" maxOccurs="1" minOccurs="1">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="action" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="transition" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="to" type="state_pointer_type" use="required"/>    
                                    <xs:attribute name="probability" type="probability_type" use="required"/>    
                                    <xs:attribute name="reward" type="xs:decimal" use="required"/>    
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="id_type" use="required"/>    
                        <xs:attribute name="title" type="title_type" use="required"/>    
                        <xs:attribute name="from" type="state_pointer_type" use="required"/>    
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== soroush/libmarl-protocols/test/sample.xml
<?xml version="1.0"?>
<environment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="mdp.xsd">
    <title>Random Problem</title>
    <description>
        Dimensions: 1000 x 1000
        Number of points: 10
    </description>
    <states>
        <state id="0" title="S0"/>
        <state id="1" title="S1"/>
        <state id="2" title="S2"/>
        <state id="3" title="S3"/>
        <state id="4" title="S4"/>
        <state id="5" title="S5"/>
        <state id="6" title="S6"/>
        <state id="7" title="S7"/>
        <state id="8" title="S8"/>
        <state id="9" title="S9"/>
    </states>
    <actions>
        <action id="0" from="S1" title="A0">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="1" from="S2" title="A1">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="1" from="S2" title="A1">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="2" from="S6" title="A2">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="2" from="S6" title="A2">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="3" from="S1" title="A3">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="3" from="S3" title="A3">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="4" from="S1" title="A4">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="4" from="S1" title="A4">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="5" from="S6" title="A5">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="5" from="S6" title="A5">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="6" from="S3" title="A6">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="6" from="S2" title="A6">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="7" from="S0" title="A7">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="7" from="S0" title="A7">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="8" from="S6" title="A8">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="8" from="S6" title="A8">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="9" from="S2" title="A9">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="9" from="S0" title="A9">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="10" from="S4" title="A10">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="10" from="S4" title="A10">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="11" from="S6" title="A11">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="11" from="S6" title="A11">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="12" from="S0" title="A12">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="12" from="S4" title="A12">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="13" from="S3" title="A13">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="13" from="S3" title="A13">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="14" from="S6" title="A14">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="14" from="S6" title="A14">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="15" from="S4" title="A15">
            <transition probability="1.0" to="S6" reward="0.0"/>
        </action>
        <action id="15" from="S1" title="A15">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="16" from="S3" title="A16">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="16" from="S3" title="A16">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="17" from="S7" title="A17">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="17" from="S7" title="A17">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="18" from="S1" title="A18">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="18" from="S5" title="A18">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="19" from="S1" title="A19">
            <transition probability="1.0" to="S5" reward="1.0"/>
        </action>
        <action id="19" from="S1" title="A19">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="20" from="S7" title="A20">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="20" from="S7" title="A20">
            <transition probability="1.0" to="S5" reward="1.0"/>
        </action>
        <action id="21" from="S5" title="A21">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="21" from="S4" title="A21">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="22" from="S0" title="A22">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="22" from="S0" title="A22">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="23" from="S8" title="A23">
            <transition probability="1.0" to="S0" reward="0.0"/>
        </action>
        <action id="23" from="S8" title="A23">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="24" from="S4" title="A24">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="24" from="S3" title="A24">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="25" from="S4" title="A25">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="25" from="S4" title="A25">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="26" from="S8" title="A26">
            <transition probability="1.0" to="S4" reward="0.0"/>
        </action>
        <action id="26" from="S8" title="A26">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="27" from="S3" title="A27">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="27" from="S7" title="A27">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="28" from="S3" title="A28">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="28" from="S3" title="A28">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="29" from="S8" title="A29">
            <transition probability="1.0" to="S3" reward="0.0"/>
        </action>
        <action id="29" from="S8" title="A29">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="30" from="S7" title="A30">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="30" from="S5" title="A30">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="31" from="S7" title="A31">
            <transition probability="1.0" to="S5" reward="1.0"/>
        </action>
        <action id="31" from="S7" title="A31">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="32" from="S8" title="A32">
            <transition probability="1.0" to="S7" reward="0.0"/>
        </action>
        <action id="32" from="S8" title="A32">
            <transition probability="1.0" to="S5" reward="1.0"/>
        </action>
        <action id="33" from="S5" title="A33">
            <transition probability="1.0" to="S8" reward="0.0"/>
        </action>
        <action id="33" from="S2" title="A33">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="34" from="S1" title="A34">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="34" from="S1" title="A34">
            <transition probability="1.0" to="S9" reward="0.0"/>
        </action>
        <action id="35" from="S9" title="A35">
            <transition probability="1.0" to="S1" reward="0.0"/>
        </action>
        <action id="35" from="S9" title="A35">
            <transition probability="1.0" to="S2" reward="0.0"/>
        </action>
        <action id="36" from="S2" title="A36">
            <transition probability="1.0" to="S9" reward="0.0"/>
        </action>
